version: 2
updates:
  # Updates for Gradle dependencies used in the app
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: com.h2database:h2
