spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:h2:mem:security_jwt;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging.level.eu.fraho.spring: DEBUG
fraho:
  jwt:
    token:
      cookie:
        enabled: true
        secure: false
      header:
        enabled: false
    refresh:
      cookie:
        enabled: true
        secure: false
